version: '3'

services:
  nginx:
    image: nginx:1.17
    restart: always
    ports:
      # laravel backend api server
      - 8080:8080
    working_dir: ${APP_PATH_CONTAINER}
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=i001.ru
      - NGINX_PORT=80
    depends_on:
      - php
    links:
      - php

  nodejs:
    image: node:10.16.3-alpine
    restart: always
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}/frontend
    ports:
      - 80:8888
    command: >
      sh -c "yarn install && yarn run start"

  php:
    build: ./php
    restart: always
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}/backend

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  composer:
    image: composer
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}/backend
    command: composer install

  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./storage/redis/data:/data