version: '3'

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=i001.ru
      - NGINX_PORT=80
    depends_on:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - ./src:/usr/share/nginx/html