version: '3'

services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
    environment:
      - NGINX_HOST=i001.ru
      - NGINX_PORT=80